### ISSUE TITLE
How do I keep track of matched orders?

### ISSUE THREAD

**Issue by sandeepmukh** [Kautenja/limit-order-book#3]
This library seems awesome and I'd like to use it to simulate trading. How do I keep track of how orders were matched and how much size was filled by which orders, etc?

**Comment by Kautenja** [comment]
Hi thanks! The purpose of this particular code is more for book reconstruction and order stream tracing. However, I have another repo, [CBOE-emulator](https://github.com/Kautenja/CBOE-emulator), that is based on this same limit order book model and includes a full network stack based on the CBOE networking specification. That may be more like what you are looking for to do simulation and keep track of order events.
